[build-system]
requires = [
  "setuptools",
  "setuptools-scm[toml]",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.black]
line-length = 100

[tool.pytest.ini_options]
addopts = "-ra"
pythonpath = "docs"
testpaths = ["docs", "tests"]
