name: test

on: [push, pull_request]

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: ["tests", "test-docs"]
        os: [ubuntu-latest, windows-latest]
        include:
          - name: "tests"
            python: "3.10"
            tox_env: "py310"
          - name: "test-docs"
            python: "3.10"
            tox_env: "test-docs"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}
